openapi: 3.1.0
info:
  title: Minimal API
  version: 1.0.0
  description: A minimal valid OpenAPI 3.1 specification

servers:
  - url: https://api.example.com
    description: Production server

paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the API
      operationId: get-health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
